### PR TITLE
auto init and downloading necessary files at first run

### PR DESCRIPTION
**Pull request by kostapc**
(init.bat ported to java)
in properties file all download URL's can be set;
if some fie is missing - it will be downloaded again.
*.exe files temporary located in my fork, in properties URL's have to be replaced by official ones. I place my own due to original releases of windows binary not available outside of windows wallet zip file;

### CODE REVIEW

**Comment by kostapc** [comment]
any news on this?

**Comment by kostapc** [comment]
*.exe files removed from repository.

**Comment by renium9** [comment]
Your PR is specialized in windows, so merge it into a new branch.

**Comment by kostapc** [comment]
as i understand - at now swing-wallet primary used as windows wallet. It's easy to create swing-wallet multi platform, but it need to create prebuild daemons for every platform (win, mac, linux).

**Pull request merged**
